-- Sazal Study: Previous Year Papers setup
-- Run this in Supabase Dashboard > SQL Editor.
-- Adds a separate table; does not alter notes or quiz_questions.
create table if not exists public.previous_year_papers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title text not null,
  board text not null,
  class_level text not null,
  subject text not null,
  year integer not null check (year between 1900 and 2100),
  file_url text not null,
  file_name text,
  file_type text not null default 'application/pdf',
  is_published boolean not null default false,
  created_by uuid references auth.users(id) on delete set null
);

alter table public.previous_year_papers enable row level security;
-- Public visitors may only read published papers.
drop policy if exists "Published papers are publicly readable" on public.previous_year_papers;
create policy "Published papers are publicly readable"
  on public.previous_year_papers for select to anon, authenticated
  using (is_published = true);
-- Admin UI uses Supabase Auth. For this starter setup, signed-in users may manage paper rows.
-- If your Supabase Auth permits public sign-ups, disable them or replace these policies with
-- an explicit admin-user allowlist before relying on this for production.
drop policy if exists "Signed-in admins can view all papers" on public.previous_year_papers;
create policy "Signed-in admins can view all papers"
  on public.previous_year_papers for select to authenticated
  using (auth.uid() = created_by);
drop policy if exists "Signed-in users can insert papers" on public.previous_year_papers;
create policy "Signed-in users can insert papers"
  on public.previous_year_papers for insert to authenticated
  with check (auth.uid() = created_by);
drop policy if exists "Signed-in users can update papers" on public.previous_year_papers;
create policy "Signed-in users can update papers"
  on public.previous_year_papers for update to authenticated
  using (auth.uid() = created_by) with check (auth.uid() = created_by);
drop policy if exists "Signed-in users can delete papers" on public.previous_year_papers;
create policy "Signed-in users can delete papers"
  on public.previous_year_papers for delete to authenticated
  using (auth.uid() = created_by);
revoke all on public.previous_year_papers from anon;
grant select on public.previous_year_papers to anon;
revoke all on public.previous_year_papers from authenticated;
grant select, insert, update, delete on public.previous_year_papers to authenticated;
grant usage, select on sequence public.previous_year_papers_id_seq to authenticated;
