-- Sazal Study Quiz Question Bank setup
-- Run once in Supabase Dashboard > SQL Editor > New query.
create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  category text not null check (category in ('GK','Reasoning','Brain Booster','Class')),
  class_level text check (class_level is null or class_level in ('Class 1','Class 2','Class 3','Class 4','Class 5','Class 6','Class 7','Class 8','Class 9','Class 10','Class 11','Class 12')),
  question text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option text not null check (upper(correct_option) in ('A','B','C','D')),
  explanation text not null default '',
  is_published boolean not null default true,
  constraint class_level_required check ((category = 'Class' and class_level is not null) or (category <> 'Class' and class_level is null))
);
create index if not exists quiz_questions_public_category_idx on public.quiz_questions (is_published, category, class_level, created_at);
alter table public.quiz_questions enable row level security;
drop policy if exists "Anyone can read published quiz questions" on public.quiz_questions;
create policy "Anyone can read published quiz questions" on public.quiz_questions for select using (is_published = true or auth.uid() is not null);
drop policy if exists "Authenticated admins can insert quiz questions" on public.quiz_questions;
create policy "Authenticated admins can insert quiz questions" on public.quiz_questions for insert to authenticated with check (auth.uid() is not null);
drop policy if exists "Authenticated admins can update quiz questions" on public.quiz_questions;
create policy "Authenticated admins can update quiz questions" on public.quiz_questions for update to authenticated using (auth.uid() is not null) with check (auth.uid() is not null);
drop policy if exists "Authenticated admins can delete quiz questions" on public.quiz_questions;
create policy "Authenticated admins can delete quiz questions" on public.quiz_questions for delete to authenticated using (auth.uid() is not null);
grant select on public.quiz_questions to anon, authenticated;
grant insert, update, delete on public.quiz_questions to authenticated;
grant usage, select on all sequences in schema public to authenticated;
